CREATE TABLE Person (
                        id  int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        username VARCHAR(30) NOT NULL,
                        age int,
                        password VARCHAR(100),
                        role VARCHAR(100)
);