create table tasks(
                      id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      title varchar(100) not null,
                      description varchar(100) not null,
                      data VARCHAR(100),
                      person_id int references  person(id) on delete set null
)