create table tasks(
                      id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      title varchar(100) not null,
                      author varchar(100) not null,
                      year int not null,
                      person_id int references  person(id) on delete set null
)